name: Daily Telegram Market Bot

on:
  schedule:
    - cron: '0 0 * * *'      # 8:00 AM SGT
    - cron: '15 13 * * *'    # 9:15 PM SGT
  workflow_dispatch:         # Manual trigger from GitHub UI

jobs:
  send-daily-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python daily_alert.py
