name: Intraday TQQQ/SQQQ Signal Bot
on:
  schedule:
    # Monday-Friday 9:30 PM SGT to 2:00 AM SGT (next day)
    # SGT is UTC+8, so we need to convert to UTC:
    # 9:30 PM SGT = 1:30 PM UTC (13:30)
    # 2:00 AM SGT = 6:00 PM UTC (18:00) previous day
    
    # Monday 9:30 PM SGT to Tuesday 2:00 AM SGT
    - cron: '30/15 13-23 * * 1'     # Monday 1:30 PM - 11:45 PM UTC
    - cron: '*/15 0-18 * * 2'       # Tuesday 12:00 AM - 6:00 PM UTC
    
    # Tuesday 9:30 PM SGT to Wednesday 2:00 AM SGT  
    - cron: '30/15 13-23 * * 2'     # Tuesday 1:30 PM - 11:45 PM UTC
    - cron: '*/15 0-18 * * 3'       # Wednesday 12:00 AM - 6:00 PM UTC
    
    # Wednesday 9:30 PM SGT to Thursday 2:00 AM SGT
    - cron: '30/15 13-23 * * 3'     # Wednesday 1:30 PM - 11:45 PM UTC
    - cron: '*/15 0-18 * * 4'       # Thursday 12:00 AM - 6:00 PM UTC
    
    # Thursday 9:30 PM SGT to Friday 2:00 AM SGT
    - cron: '30/15 13-23 * * 4'     # Thursday 1:30 PM - 11:45 PM UTC
    - cron: '*/15 0-18 * * 5'       # Friday 12:00 AM - 6:00 PM UTC
    
    # Friday 9:30 PM SGT to Saturday 2:00 AM SGT
    - cron: '30/15 13-23 * * 5'     # Friday 1:30 PM - 11:45 PM UTC
    - cron: '*/15 0-18 * * 6'       # Saturday 12:00 AM - 6:00 PM UTC

  workflow_dispatch:        # Manual trigger option

jobs:
  run-intraday-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run intraday TQQQ/SQQQ bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python intraday_tqqq_bot.py
