name: Positional TQQQ/SQQQ Swing Trading Bot
on:
  schedule:
    # Run once daily at 9:30 PM SGT (1:30 PM UTC) Monday-Friday
    - cron: '30 13 * * 1-5'
  
  workflow_dispatch:        # Manual trigger option

jobs:
  run-intraday-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run positional TQQQ/SQQQ swing bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python positional_tqqq_bot.py
